package com.example.gymapp.application

const val USER_DETAIL_PREFERENCES_NAME = "userDetailPreferences"
const val COUNTRY_CODE = "+91"
const val SCHEDULE_DISPLAY_FOR_DAYS = 3
const val DEFAULT_ACTIVITY_FOR_SESSION_SCHEDULE_LISTING = "WORKOUT"

// ALGOLIA FREE TEXT SEARCH CONSTANTS
const val ALGOLIA_APPLICATION_ID = "UV7REXJNQJ"
const val ALGOLIA_APPLICATION_KEY = "0b11699168f3d5e74cdc4bd6cdd839ed"
const val ALGOLIA_INDEX_NAME = "Gym"
